# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false

# Mod Properties
mod_id=justwalk
mod_name=JustWalk
mod_license=MIT
mod_version=1.0.0
mod_authors=Nulled
mod_description=If you think that Minecraft characters could be more realistic, instead of steady and rigid animations, this mod is just for you! JustWalk adds a variety of different player animations including epic sword animations! NOW IN MINECRAFT 1.20.1!

# Minecraft/Forge Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.0
forge_version_range=[47,)
loader_version_range=[47,)
